from app.models import MicroSkill, Skill, SkillMicroSkills, Job, JobSkills
#
# skills = ['Google Ads - Shopping',
# 'Google Ads - Shopping',
# 'Google Ads - Shopping',
# 'Google Ads - Shopping',
# 'Google Ads - Shopping',
# 'Google Ads - Shopping',
# 'Google Ads - Display',
# 'Google Ads - Display',
# 'Google Ads - Display',
# 'Google Ads - Display',
# 'Google Ads - Display',
# 'Google Ads - Display',
# 'Google Ads - Shopping',
# 'Google Ads - Display',
# 'Google Ads - Discovery',
# 'Google Ads - Discovery',
# 'Google Ads - Discovery',
# 'Google Ads - Discovery',
# 'Google Ads - Discovery',
# 'Google Ads - Discovery',
# 'Google Ads - Discovery',
# 'Google Ads - Youtube',
# 'Google Ads - Youtube',
# 'Google Ads - Youtube',
# 'Google Ads - Youtube',
# 'Google Ads - Youtube',
# 'Google Ads - Youtube',
# 'Google Ads - GMB',
# 'Google Ads - GMB',
# 'Google Ads - GMB',
# 'Google Analytics',
# 'Google Analytics',
# 'Google Analytics',
# 'Google Analytics',
# 'Google Analytics',
# 'Google Analytics',
# 'Google Analytics',
# 'Google Analytics',
# 'Google Analytics',
# 'Web and App Tracking Instrumentation',
# 'Web and App Tracking Instrumentation',
# 'Web and App Tracking Instrumentation',
# 'Web and App Tracking Instrumentation',
# 'Facebook Ads',
# 'Facebook Ads',
# 'Facebook Ads',
# 'Facebook Ads',
# 'Facebook Ads',
# 'Facebook Ads',
# 'Basic Excel',
# 'Basic Excel',
# 'Basic Excel',
# 'Basic Excel',
# 'Basic Excel',
# 'Basic Excel',
# 'Stakeholder Management',
# 'Stakeholder Management',
# 'Stakeholder Management',
# 'Stakeholder Management',
# 'Stakeholder Management',
# 'Negotiation',
# 'Negotiation',
# 'Negotiation',
# 'Negotiation',
# 'Negotiation',
# 'Workflow Management',
# 'Workflow Management',
# 'Workflow Management',
# 'Workflow Management',
# 'Google Ads Perfromance Max',
# 'Google Ads Perfromance Max',
# 'Google Ads Perfromance Max',
# 'Google Ads Perfromance Max',
# 'Google Ads Perfromance Max',
# 'Google Ads Perfromance Max',
# 'Google Ads Perfromance Max',
# 'Google Ads Perfromance Max',
# 'Google Ads Perfromance Max',
# 'Google Ads Perfromance Max',
# 'Google Ads Perfromance Max',
# 'Google Ads Perfromance Max',
# 'Google Ads Perfromance Max',
# 'Google Ads Perfromance Max',
# 'Google Ads Perfromance Max',
# 'Google Ads Text',
# 'Google Ads Text',
# 'Google Ads Text',
# 'Google Ads Text',
# 'Google Ads Text',
# 'Google Ads Text',
# 'Omnichannel Retail Basics']
#
#
# microskills =[
# 'Google Merchant Center',
# 'Google Shopping and Smart Shopping Campaigns',
# 'Google Ads Goals and Optimisation',
# 'Google Ads Audience Targeting',
# 'Google Ads Bidding Strategies',
# 'Google Ads Search Term Analysis',
# 'Performance tracking on Google Analytics',
# 'Google Merchant Center',
# 'Google Display Network',
# 'Google Ads Goals and Optimisation',
# 'Google Ads Audience Targeting',
# 'Google Ads Bidding Strategies',
# 'Goofle Ads Creatives for Display Network',
# 'Performance tracking on Google Analytics',
# 'Google Merchant Center',
# 'Google Discovery Ads Inventory',
# 'Google Ads Audience Targeting',
# 'Google Ads Bidding Strategies',
# 'Goofle Ads Creatives for Discovery Ads',
# 'Performance tracking on Google Analytics',
# 'Google Ads Goals and Optimisation',
# 'Google Youtube Ads Inventory',
# 'Google Ads Audience Targeting',
# 'Google Ads Bidding Strategies',
# 'Goofle Ads Creatives for Youtube',
# 'Performance tracking on Google Analytics',
# 'Google Ads Goals and Optimisation',
# 'Google My Business Management',
# 'Google Merchant Center',
# 'Google Ads Goals and Optimisation',
# 'Google Tags Configuration',
# 'SDK Configuration',
# 'Traffic Analysis',
# 'Conversion Analysis',
# 'Digital Marketing Reporting',
# 'Google Analytics - Google Sheet Plugin',
# 'Google Analytics Events',
# 'Google Analytics Properties',
# 'Google Analytics Audience',
# 'Google Tags Configuration',
# 'SDK Configuration',
# 'Facebook Pixel Configuration',
# 'E Commerce Events',
# 'Facebook Ads Objectives',
# 'Facebook Ads Buying',
# 'Facebook Ads Inventory',
# 'Facebook Pixel Configuration',
# 'SDK Configuration',
# 'Facebook Events Tracking',
# 'Basic Statistics',
# 'Basic Statistical Functions',
# 'Basic Data Preparation Functions',
# 'Basic Automation',
# 'Basic Reporting',
# 'Basic Data Visualization',
# 'Information and Task Alignment',
# 'Task Prioritising',
# 'Relation building',
# 'Aligning Tradeoffs',
# 'Conflict Management',
# 'Information Gathering',
# 'Relation building',
# 'Aligning Tradeoffs',
# 'Negotiation Closure',
# 'Legal Agreements',
# 'Information and Task Alignment',
# 'Task Prioritising',
# 'Task Tracking',
# 'Process optimization',
# 'Google Merchant Center',
# 'Google Performance Max Ads Inventory',
# 'Google Ads Goals and Optimisation',
# 'Google Ads Audience Targeting',
# 'Google Ads Bidding Strategies',
# 'Google Ads Search Term Analysis',
# 'Performance tracking on Google Analytics',
# 'Google Display Network',
# 'Google Discovery Ads Inventory',
# 'Google Youtube Ads Inventory',
# 'Google Text Ads Inventory',
# 'Google Shopping and Smart Shopping Campaigns',
# 'Goofle Ads Creatives for Display Network',
# 'Goofle Ads Creatives for Discovery Ads',
# 'Goofle Ads Creatives for Youtube',
# 'Google Text Ads Inventory',
# 'Google Ads Goals and Optimisation',
# 'Google Ads Audience Targeting',
# 'Google Ads Bidding Strategies',
# 'Google Ads Ad Copies for Text Ads',
# 'Performance tracking on Google Analytics',
# 'Omnichannel Retail Basics']


# for i in range(91):
#     skill = skills[i]
#     ms = microskills[i]
#     sk = Skill.objects.get(name=skill)
#     msk = MicroSkill.objects.get(name=ms)
#     SkillMicroSkills.objects.create(skill=sk, microskill=msk)
#     print("Skill microskill map inserted")

job_skill_list = [
['Assistant Marketing Manager',	'Google Ads - Shopping'	,'technical'	,5],
['Assistant Marketing Manager',	'Google Ads - Display'	,'technical'	,5],
['Assistant Marketing Manager',	'Google Ads - Discovery'	,'technical'	,5],
['Assistant Marketing Manager',	'Google Ads - Youtube'	,'technical'	,5],
['Assistant Marketing Manager',	'Google Ads - GMB'	,'technical'	,5],
['Assistant Marketing Manager',	'Google Analytics'	,'technical'	,5],
['Assistant Marketing Manager',	'Web and App Tracking Instrumentation'	,'technical'	,3],
['Assistant Marketing Manager',	'Facebook Ads'	,'technical'	,4],
['Assistant Marketing Manager',	'Basic Excel'	,'technical'	,4],
['Assistant Marketing Manager',	'Stakeholder Management'	,'non-technical'	,3],
['Assistant Marketing Manager',	'Negotiation'	,'non-technical'	,2],
['Assistant Marketing Manager',	'Workflow Management'	,'non-technical'	,3],
['Assistant Marketing Manager',	'Google Ads Perfromance Max'	,'technical'	,5],
['Assistant Marketing Manager',	'Google Ads Text'	,'technical'	,5],
['Assistant Marketing Manager',	'Omnichannel Retail Basics'	,'technical'	,4]
]

for js in job_skill_list:
    job_name = js[0]
    skill_name = js[1]
    skill_type = js[2]
    skill_weight = js[3]
    job = Job.objects.get(title=job_name)
    skill = Skill.objects.get(name=skill_name)
    JobSkills.objects.create(job=job, skill=skill, skill_type=skill_type, weight=skill_weight)