# Generated by Django 4.0.5 on 2022-06-11 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MicroSkill_Prerequisite',
            new_name='MicroSkillPrerequisite',
        ),
        migrations.RenameModel(
            old_name='Skill_MicroSkills',
            new_name='SkillMicroSkills',
        ),
    ]
