# Generated by Django 4.0.5 on 2022-06-12 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_microskill_prerequisite_microskillprerequisite_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobskills',
            old_name='job_title',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='jobskills',
            old_name='skill_title',
            new_name='skill',
        ),
        migrations.RemoveField(
            model_name='microskill',
            name='skills',
        ),
    ]
