# Generated by Django 4.0.5 on 2022-06-12 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_job_title_jobskills_job_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microskill',
            name='weight',
        ),
    ]
