# Generated by Django 4.0.5 on 2022-06-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_microskill_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillmicroskills',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
